### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [nikitavoloboev/privacy-respecting#19]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by nikitavoloboev** [comment]
Sounds awesome @redmusic27 

A nice logo would really improve this project. Thank you very much. 💜

**Comment by redmusic27** [comment]
Okay sir. I will start to make a logo for you. if it is ready I will be back. I do not ask for payment. I'm happy if later my logo you directly use

**Comment by redmusic27** [comment]
Hello sir, I came back with my concept logo. I hope you like it

# CONCEPT #
![concept](https://user-images.githubusercontent.com/37577374/38470297-dc2c6406-3b8a-11e8-8099-705def4085da.jpg)
# LOGOMARK #
![logomark](https://user-images.githubusercontent.com/37577374/38470298-dc6880a8-3b8a-11e8-86c1-4db1b751de24.jpg)
# LOGOTYPE - HORIZONTAL #
![logotype-horizontal](https://user-images.githubusercontent.com/37577374/38470299-dca836b2-3b8a-11e8-97f5-4eec4eca4ed9.jpg)
# LOGOTYPE - VERTICAL #
![logotype-vertical](https://user-images.githubusercontent.com/37577374/38470300-dce6a0f0-3b8a-11e8-8e4e-ce9670139e1f.jpg)

What do you think sir?
If you agree that this logo will be used, I will immediately create the complete file for you

**Comment by redmusic27** [comment]
I understand what you mean, so i will make it all versions like png, svg, and ai right now. I'm very happy if you like it sir.

**Comment by redmusic27** [comment]
Hello sir, Im done.
All vector & editable files is HERE. You can download it.
https://drive.google.com/open?id=1LTrQhecDo03Cz1ykSzB7vXbjLoKg178-
Try to check if there is still less. Let me know

**Comment by redmusic27** [comment]
Hello sir, its done. you can check all vector & editable files is HERE. You can download it. 
https://drive.google.com/open?id=1LTrQhecDo03Cz1ykSzB7vXbjLoKg178-

I sent pr. Please check it to 
#28

**Comment by nikitavoloboev** [comment]
Hi @redmusic27. I added the logo to the repository. Thank you very much. It turned out really well. 💜

**Comment by nikitavoloboev** [comment]
I also added a [Thanks](https://github.com/nikitavoloboev/privacy-respecting#thanks) section mentioning your name. Really appreciate the work you made on the logo.

**Comment by redmusic27** [comment]
Enjoy sir, I was happy enough to be able to help and thank you for tagging my name

**Comment by nikitavoloboev** [comment]
Hi @redmusic27. Is it possible to upload a version of [this image](https://drive.google.com/drive/folders/1-izE2mE_ShNLKAOq_J_GFTx_ny91-h5u) but non transparent. So it has white background?

**Comment by redmusic27** [comment]
Of course, you just change the vector format to JPG sir

**Comment by nikitavoloboev** [comment]
Hi @redmusic27 

If you wish and enjoy making logos, there is one other list of [various curated lists](https://github.com/learn-anything/curated-lists#readme) that would love to have a beautiful and memorable logo. It's similar to [awesome lists](https://github.com/sindresorhus/awesome#readme).

Would love to discuss it more on how to make it interesting with you. If you are interested, you can [open an issue there](https://github.com/learn-anything/curated-lists/issues/new). 🙂

**Comment by redmusic27** [comment]
JPEG VERSION : https://drive.google.com/folderview?id=1i2KCZkVQ8iGvTyYY3XIvjsqN8a3BHZqt

**Comment by redmusic27** [comment]
wow, sure I will try to make a beautiful logo for it
