### ISSUE TITLE
Check out prism-break.org

### ISSUE THREAD

**Issue by nextgenthemes** [nikitavoloboev/privacy-respecting#2]
https://prism-break.org/en/all/

**Comment by briatte** [comment]
But PRISM Break is not up-to-date, right? I vaguely remember reading something about that.

**Comment by millette** [comment]
It looks like the [source is still updated](https://github.com/nylira/prism-break/tree/master/source/db) and [last month more issues were closed than opened](https://github.com/nylira/prism-break/pulse/monthly) so that's a good sign. Because the page is/was so popular, the project still has over 300 open issues, Also note the footer of <https://prism-break.org/en/> mentions:

> Updated: 2017-08-21

**Comment by briatte** [comment]
Good, thanks for the info!

**Comment by nextgenthemes** [comment]
@millette I do not get what you are saying and what is supposedly "outdated" about it when the last change was 3 days ago? You say the source is outdated. What you actually mean is the site is outdated while the source on Github seems well maintained.

This project has a pretty small list compared to prism-break. Not sure if prism-break is about services and software or just software. I did not even know it was on Github, but I guessed so without searching.

So giving that there is such a huge, old, maintained, extensive project with basically the exact same goal I feel it may not even be worth doing this. So I just wanted to mention it because the maintainers or contributers of this may want to copy paste everything from there or just decide to help that project instead.

That fact that it has many open issues is a good think and a bad thing at that same time. It shows many people are drawn to it and want to make it better and it also shows that who maintains it may not have/invest enough time to deal with that. There should probably new maintainers added ... but overall I think its still far ahead of this so I just wanted to mention it because I guessed not everyone knew about it.

**Comment by briatte** [comment]
To be clear, I am the one who raised the question about whether or not the PRISM Break website was still up-to-date. And yes, I meant the website, not the GitHub repo.

I remember visiting the website around June or early July, and got the impression then that the website had thrived a few years ago but had then stopped updating most of its content.

Re: whether this repo should exist separately from PRISM Break, I would find any definite statement on that point to be, at best, very premature.

**Comment by millette** [comment]
@nextgenthemes Ahum... I was providing details to support your suggestion, not sure where your confusion comes from. Are you trying to tell me my tiny beard looks like a tiny coffee mug? ;-)

**Comment by nextgenthemes** [comment]
You were trying to support my suggestion by claiming its outdated and pointing to the many open issues it has? Well you may want to be more clear next time because it sounded like the exact opposite.

Its sounded like "yeah this site sucks, its outdated and no one cares for the many open issues so just forget about it"

Prism break should have some automation that the github changes are reflected on the website. In fact it could be hosted on github, everything could sit in the gh-pages branch, not sure how its build but I have seen https://github.com/PrismJS/prism do this. What a funny coincidence with the name. But I should probably suggest it there ...

**Comment by briatte** [comment]
In all honesty, @nextgenthemes, you misunderstood a well-documented answer to my question. That's on you, not on the person who answered.

As far as I'm concerned, the answer was clear and not at all dismissive of the website that it referred to.

**Comment by millette** [comment]
Final attempt with a straight face.

1. @nextgenthemes proposed we have a look at prism-break
1. @briatte mentions it might be outdated
1. @millette points to the actual information to support the OP idea

Where you "heard my tone" is all on you @nextgenthemes. I'm almost sure you're not a troll, just that you read a bit too much or was confused by @briatte first short response - and that's really whom I was responsing too.

Enough of this silly tangent. I never thought I'd have to explain myself on github like this and it's taken too much of our time already.

P.S.: thank you @briatte for trying to clarify things for me.

**Comment by nextgenthemes** [comment]
@briatte Yeah you can call a comment "well-documented" that claims a project is "outdated" that does by mo means need to be updated daily. The actually information how much "outdated" the site was was actually **not** in there. I think it was 2 weeks or 2 months or something and the source the last github update was 3 days also **not** mentioned the "well-documented" comment. Not like you suggested "thrived for years and then stopped updating". That comment also confused the source with the website but hey who cares. Such a "well-informed" comment when 3 clicks basically give you better information. I must be really stupid for not agreeing. Also pointing out only negatives is easy understood the way I did. There was no indication at all that he supported this, the opposite is the case Again: To me it sounded like "hey its outdated, no one cares about this many issues so go ahead and reinvent the wheel".

Now there are several links to prism break and other projects in this list now. And at the time of writing the prism break website has a "Updated: 2017-09-04" note.

**Comment by millette** [comment]
@nextgenthemes Last comment from my end on this...

@briatte asked
> But PRISM Break is not up-to-date, right?

To which I replied
> It looks like the source is still updated

Perhaps you're mixing comments?
