### ISSUE TITLE
Don't link to the Guardian WhatsApp "backdoor" article

### ISSUE THREAD

**Issue by FiloSottile** [nikitavoloboev/privacy-respecting#27]
> WhatsApp - Uses Signal Protocol but logs all the metadata around messages

The Guardian article linked there was wildly misleading and bad journalism, as denounced by the authors of Signal themselves, amongst many other experts. Also, it has nothing to do with "logging all the metadata".

Please don't spread that unfortunate FUD.

* https://techcrunch.com/2017/01/22/whatsapp-signal-and-dangerously-ignorant-journalism/
* http://technosociology.org/?page_id=1687

**Comment by nikitavoloboev** [comment]
Thank you @FiloSottile. I apologise for including the link, I have now removed it.

I am not sure where should WhatsApp be on this list. I know it uses Signal protocol and thus all chats are E2E but I also know that WhatsApp sends entire user's contacts books to the FB servers and I read that FB will still log a lot of metadata around messages which is very revealing.

Thank you for any feedback on this.

**Comment by FiloSottile** [comment]
I don't have a strong opinion on that. As for lots of things in security, it involves tradeoffs and isn't binary. Mentioning that unlike others is e2e (and good e2e) is important, but you already do that. I tend to recommend WA because the good UX keeps people using e2e.
