### ISSUE TITLE
Is there an alternative to Google Keep?

### ISSUE THREAD

**Issue by sdushantha** [nikitavoloboev/privacy-respecting#42]
[Google Keep](https://keep.google.com) is a pretty nice app to keep notes. But since it is made by Google, I do have my doubts when it comes to privacy. Are there any nice once out there that has good UI and has really good privacy?

**Comment by kszyrztof** [comment]
Laverna or Simplenote seems to be a good alternative, but I haven't had the opportunity to test them out yet: https://alternativeto.net/software/laverna/ https://alternativeto.net/software/simplenote/

**Comment by nikitavoloboev** [comment]
Apps where you can control the data that is being stored that is not sent to a cloud you don't trust are good alternatives.

I personally use Sublime Text for my notes.
