### ISSUE TITLE
Revise Vivaldi as a good alternative

### ISSUE THREAD

**Issue by Atavic** [nikitavoloboev/privacy-respecting#44]
Vivaldi browser has an [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier), that's a Unique User ID.

>It does install per a Unique User ID

See: https://forum.vivaldi.net/topic/11413/privacy-does-v-create-unique-installation-id-for-google-other-privacy-mods-of-srware-s-iron

**Comment by nikitavoloboev** [comment]
I guess we can remove Vivaldi from the list. It seems like a dead browser to me personally. Thanks for the link.
