### ISSUE TITLE
What about GitHub? Microsoft is taking over.....should GitLab be an alternative?

### ISSUE THREAD

**Issue by sdushantha** [nikitavoloboev/privacy-respecting#45]
I know this a strange one, but should there be an alternative for GitHub now because Microsoft is taking over? I might slowly move to GitLab.

**Comment by Jpfonseca** [comment]
@sdushantha I would do it , and  have a mirror on Bitbucket too.

**Comment by nikitavoloboev** [comment]
Perhaps we should create a new category named `Code hosting`?

**Comment by sdushantha** [comment]
Since we are talking about GitLab, @nikitavoloboev, are you going to move this repo to GitLab?

**Comment by nikitavoloboev** [comment]
We can certainty mirror this repository to GitLab but this GitHub repository will stay. GitHub still is and I believe will be the defacto place where open source happens.

**Comment by rackyman** [comment]
I don't think Microsoft taking over will create issues, on the other hand it will improve Github's security.
