### ISSUE TITLE
New VPNs

### ISSUE THREAD

**Issue by FreddyMarsden** [nikitavoloboev/privacy-respecting#66]
[IVPN](https://www.privacytools.io/providers/vpn/#ivpn) - they even [ran an article saying don't use a VPN](https://www.ivpn.net/blog/why-you-dont-need-a-vpn/), pretty good company.
[Azire](https://www.azirevpn.com/) - all the desired features of a privacy-respecting VPN, only problem is that they haven't been audited.

**Comment by nikitavoloboev** [comment]
PR would be nice :)
