### ISSUE TITLE
Update Messengers

### ISSUE THREAD

**Issue by FreddyMarsden** [nikitavoloboev/privacy-respecting#68]
**Delist:** [Keybase](https://github.com/privacytools/privacytools.io/issues/1894), [Silence](https://madaidans-insecurities.github.io/messengers.html) and [Telegram](https://github.com/tycrek/degoogle/issues/29).
**Add:** [Status](https://status.im/) - Encrypted instant messenger with an integrated Ethereum wallet (cryptocurrency) that also includes support for DApps (decentralized apps) (web apps in a curated store). Uses the Waku protocol (a fork of Whisper) for P2P communication. Only available for iOS and Android.

**Comment by nikitavoloboev** [comment]
Can you PR?
