### ISSUE TITLE
New Category Suggestion: Private Frontends

### ISSUE THREAD

**Issue by spikecodes** [nikitavoloboev/privacy-respecting#73]
Many social platforms are closed-sourced and invasive. Though, some have private alternative front-ends that allow users to browse the site free of trackers, ads and cookies by proxying their web traffic through the alternative client.

Examples:
- YouTube -> [Invidious](https://github.com/iv-org/invidious)
- Twitter -> [Nitter](https://github.com/zedeus/nitter)
- Instagram -> [Bibliogram](https://github.com/cloudrac3r/bibliogram)
- Reddit -> [Libreddit](https://github.com/spikecodes/libreddit/)

This would be a great addition to provide resources to those who don't want to ditch a platform altogether (services like YouTube and Twitter are especially hard to avoid on the internet) but still want to browse them privately.

**Comment by nikitavoloboev** [comment]
I like this idea. Can you make a PR? ❤️

**Comment by spikecodes** [comment]
Definitely! #74
